### ISSUE TITLE
Features url for clients change in v3.

### ISSUE THREAD

**Issue by ivarconr** [onybo/unleash-client-core#2]
In order to ease the process of having different auth mechanisms for clients and for the admin UI, and because unleash-server must provide backward comparability for clients, it was decided to not share API endpoints between `unleash-frontend` (Aadmin UI) and `unleash-clients`. 

Starting from v3.x all clients should use `/client/features` to query toggles. `/client/register`) and `/client/metrics` remains the same. 

This requires a change in this line:
https://github.com/onybo/unleash-client-core/blob/master/src/unleash/util/UnleashURLs.cs#L8

**Comment by onybo** [comment]
thanks for letting me know about this. Fixing now.
